# These are supported funding model platforms
# Uncomment and replace with your actual usernames/URLs

# github: yourusername
# patreon: yourusername
# open_collective: yourusername
# ko_fi: yourusername
# tidelift: yourusername
# community_bridge: yourusername
# liberapay: yourusername
# issuehunt: yourusername
# otechie: yourusername
# custom: https://yourwebsite.com/donate